//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARSDATA
    {
        public int car_id { get; set; }
        public string car_model { get; set; }
        public short fuel_supply { get; set; }
        public string locence_plate { get; set; }
        public int location { get; set; }
        public int mileage { get; set; }
        public string date_of_the_last_technical_inspection { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual CarStatuses CarStatuses { get; set; }
    }
}
