//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarStatuses
    {
        public CarStatuses()
        {
            this.CARSDATA = new HashSet<CARSDATA>();
        }
    
        public int status_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<CARSDATA> CARSDATA { get; set; }
    }
}
