//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.USERDATA = new HashSet<USERDATA>();
        }
    
        public int roleID { get; set; }
        public string role_name { get; set; }
    
        public virtual ICollection<USERDATA> USERDATA { get; set; }
    }
}
