//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERDATA
    {
        public int USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string CARD_NUMBER { get; set; }
        public short POINTS { get; set; }
        public decimal MILEAGE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public int roleid { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
